# Generated by Django 3.1.7 on 2024-09-23 11:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(db_index=True, max_length=150)),
                ('productid', models.SlugField(max_length=100)),
                ('brandproductid', models.SlugField(max_length=100)),
                ('fakeprice', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('productprice', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('productdetail', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('promotion', models.BooleanField(default=False)),
                ('promotiontime', models.DateField(blank=True, null=True)),
                ('lazada', models.CharField(blank=True, max_length=500, null=True)),
                ('shopee', models.CharField(blank=True, max_length=500, null=True)),
                ('nocnoc', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('delay_delivery', models.BooleanField(default=False)),
                ('askbefore', models.BooleanField(default=False)),
                ('youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='manual/')),
            ],
            options={
                'ordering': ('productname',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=150)),
                ('brand_pic', models.ImageField(max_length=500, upload_to=product.models.brand_img)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('priority', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('tel', models.CharField(blank=True, max_length=60, null=True)),
                ('contact_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('stop', models.DateField(blank=True, null=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('file', models.ImageField(max_length=500, upload_to=product.models.product_img)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.allproduct')),
            ],
        ),
        migrations.AddField(
            model_name='allproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand'),
        ),
        migrations.AddField(
            model_name='allproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.category'),
        ),
        migrations.AlterIndexTogether(
            name='allproduct',
            index_together={('id', 'productid')},
        ),
    ]
