# Generated by Django 3.1.7 on 2024-09-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproduct',
            name='brandproductid',
        ),
    ]
