# Generated by Django 3.1.7 on 2024-09-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_allproduct_brandproductid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='brandproductid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
