# Generated by Django 3.1.7 on 2024-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_allproduct_brandproductid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='gp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
