# Generated by Django 3.1.7 on 2024-09-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listptomo',
            old_name='product_id',
            new_name='brandproductid',
        ),
    ]
