# Generated by Django 3.1.7 on 2024-09-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20240924_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listptomo',
            old_name='brandproductid',
            new_name='product_id',
        ),
    ]
