# Generated by Django 3.1.7 on 2024-09-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20240924_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listptomo',
            name='product_id',
        ),
    ]
