# Generated by Django 3.1.7 on 2024-09-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_allproduct_brandproductid'),
        ('promotion', '0004_remove_listptomo_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listptomo',
            name='brandproductid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brandproductids', to='product.allproduct'),
        ),
    ]
