# Generated by Django 3.1.7 on 2024-09-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_allproduct_brandproductid'),
        ('promotion', '0006_auto_20240926_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listptomo',
            new_name='listpromo',
        ),
    ]
