# Generated by Django 3.1.7 on 2024-09-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newproduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='youtube_link',
        ),
    ]
