# Generated by Django 3.1.7 on 2024-09-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproduct', '0002_remove_new_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
