# Generated by Django 3.1.7 on 2024-07-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cancel_date',
        ),
    ]
