# Generated by Django 3.1.7 on 2024-07-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_cancel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancel_date',
            field=models.DateField(blank=True, help_text='วันที่ยกเลิก', null=True),
        ),
    ]
