# Generated by Django 3.1.7 on 2024-08-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_cancel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='overall',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ler_delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('ler_expected_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverys', to='invoice.invoice')),
            ],
        ),
    ]
