# Generated by Django 3.1.7 on 2024-08-25 08:29

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20240808_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ler_pic1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invoice.models.pic1_img),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ler_pic2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invoice.models.pic2_img),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ler_pic3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invoice.models.pic3_img),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ler_pic4',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invoice.models.pic4_img),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ler_pic5',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invoice.models.pic5_img),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ler_pic6',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invoice.models.pic6_img),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ler_signature',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invoice.models.signature_img),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='brance',
            field=models.CharField(blank=True, help_text='สาขากรณ๊ไม่ใช่สำนักงานใหญ่', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='etax',
            field=models.BooleanField(default=False, help_text='ส่ง/ออก e-tax แล้ว'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='evenote',
            field=models.TextField(blank=True, help_text='ข้อความถึง supplier', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ler_note',
            field=models.TextField(blank=True, help_text='ข้อความถึงขนส่ง', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ler_pickup',
            field=models.BooleanField(default=False, help_text='ไปรับสินค้าเอง'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='map_pic',
            field=models.ImageField(blank=True, help_text='แผนที่', max_length=500, null=True, upload_to=invoice.models.map_img),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receive_pic',
            field=models.ImageField(blank=True, help_text='ใบเสร็จ', max_length=500, null=True, upload_to=invoice.models.receive_img),
        ),
    ]
