# Generated by Django 3.1.7 on 2024-09-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20240827_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='showroom',
            field=models.BooleanField(default=False),
        ),
    ]
