# Generated by Django 3.1.7 on 2024-10-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoice_showroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True, help_text='เลข edi', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='comment2',
            field=models.TextField(blank=True, help_text='ติดตั้ง/ไม่ติดตั้ง', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='comment3',
            field=models.TextField(blank=True, help_text='ข้อความถึง supplier3', null=True),
        ),
    ]
