# Generated by Django 3.1.7 on 2024-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20241015_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='comment',
            field=models.CharField(blank=True, help_text='เลข edi', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comment2',
            field=models.CharField(blank=True, help_text='ติดตั้ง/ไม่ติดตั้ง', max_length=50, null=True),
        ),
    ]
