# Generated by Django 3.1.7 on 2024-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20241016_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='overall_invoice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
