# Generated by Django 3.1.7 on 2024-06-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ยอดค่าน้ำมัน', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trans',
            name='mile_start',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='ไมล์ก่อนออก', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trans',
            name='mile_stop',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='ไมล์จบงาน', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trans',
            name='other_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ยอดค่าใช้จ่ายอื่นๆ', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trans',
            name='other_cost_remark',
            field=models.CharField(blank=True, help_text='ค่าใช้จ่ายอะไร', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='trans',
            name='toll_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ยอดค่าทางด่วน', max_digits=10, null=True),
        ),
    ]
