# Generated by Django 3.1.7 on 2024-06-12 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20240612_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trans',
            name='id',
        ),
        migrations.AddField(
            model_name='trans',
            name='outsouce_trans',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ค่าขนส่ง', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trans',
            name='send_date',
            field=models.DateField(blank=True, default=datetime.date.today, primary_key=True, serialize=False, unique=True),
        ),
    ]
