# Generated by Django 3.1.7 on 2024-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20240612_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='remark',
            field=models.CharField(blank=True, help_text='หมายเหตุ', max_length=300, null=True),
        ),
    ]
